language: node_js
node_js:
- node

sudo: required

services:
- docker

before_install:
- docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash

script:
- mkdir build && mkdir dist && cd build
- docker exec emconfigure cmake ..
- docker exec emmake make