language: node_js
node_js:
- node

sudo: required

services:
- docker

before_install:
- docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
- docker exec -it emscripten apt update
- docker exec -it emscripten apt -y install autoconf libtool dh-autoreconf

script:
- docker exec -it emscripten /bin/sh -c 'mkdir build && cd build && emconfigure cmake .. && emmake make'